export const LISTAR_MATERIAIS = 'LISTAR_MATERIAIS';

export const CRIAR_MATERIAL = 'CRIAR_MATERIAL';

export const LISTAR_HISTORICO_MATERIAL = 'LISTAR_HISTORICO_MATERIAL';

export const LIMPA_HISTORICO_MATERIAL = 'LIMPA_HISTORICO_MATERIAL';

export const ALTERAR_MATERIAL = 'ALTERAR_MATERIAL';