export const CRIAR_RECEITA = 'CRIAR_RECEITA';

export const SALVAR_DADOS_CONSOLIDADOS = 'SALVAR_DADOS_CONSOLIDADOS';

export const LIMPA_DADOS_CONSOLIDADOS = 'LIMPA_DADOS_CONSOLIDADOS';

export const LISTAR_RECEITAS = 'LISTAR_RECEITAS';

export const LISTAR_HISTORICO_RECEITA = 'LISTAR_HISTORICO_RECEITA';

export const LIMPAR_HISTORICO_RECEITA = 'LIMPAR_HISTORICO_RECEITA';

export const ALTERAR_RECEITA = 'ALTERAR_RECEITA';